SCREEN_HEIGHT = 1080
SCREEN_WIDTH = 1920

FIELD_HEIGHT = 760  # decreased a little more
FIELD_WIDTH = 1200  # decreased a little more

START_FIELD_WIDHT = (SCREEN_WIDTH - FIELD_WIDTH) / 2 # 326
START_FIELD_HEIGHT = (SCREEN_HEIGHT - FIELD_HEIGHT) / 2 # 145

FIELD_GK_WIDTH = 161
FIELD_GK_HEIGHT = 300

START_FIELD_GK_WIDHT = START_FIELD_WIDHT
START_FIELD_GK_HEIGHT = START_FIELD_HEIGHT + ((FIELD_HEIGHT - FIELD_GK_HEIGHT) / 2) 

GK_POST_WIDTH = 10
GK_POST_HEIGHT = 60